#!/usr/bin/env node
/**
 * Postinstall script for @mkhitar99/secret-scrubber
 * Auto-generates scrubber.config.json and .npmignore in the user's project
 */

const fs = require('fs');
const path = require('path');

const DEFAULT_CONFIG = {
  rules: {
    redactEmails: true,
    redactIPs: true,
    redactLocalPaths: true,
    redactNames: false,
    customPatterns: [],
  },
  safetyLevel: 'BALANCED',
  exclude: ['node_modules/**', '.git/**', 'dist/**'],
  names: [],
  piiPatterns: [],
  sensitiveFiles: ['.env', '.env.*', '*.pem', '*.key'],
  npmIgnore: [],
};

const DEFAULT_NPMIGNORE = `# Generated by @mkhitar99/secret-scrubber
# Prevents sensitive files from being published to npm

# Environment files
.env
.env.*

# Secrets and keys
*.pem
*.key
*.p12
*.pfx
*.jks
*.keystore

# Scrubber output files (contain secrets info)
scrubber-report.*
scrubbed-*
scrubber.config.json
.scrubberrc.json
.scrubberignore

# Test coverage
coverage/

# OS files
.DS_Store
*.tgz
`;

function main() {
  // Get the user's project root (where npm install was run)
  const userProjectRoot = process.env.INIT_CWD || process.cwd();
  
  // Don't run if we're installing within the secret-scrubber package itself
  if (userProjectRoot.includes('secret-scrubber') && fs.existsSync(path.join(userProjectRoot, 'src'))) {
    console.log('[secret-scrubber] Installing within package itself - skipping config generation');
    return;
  }

  // Generate scrubber.config.json if it doesn't exist
  const configPath = path.join(userProjectRoot, 'scrubber.config.json');
  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(configPath, JSON.stringify(DEFAULT_CONFIG, null, 2) + '\n', 'utf-8');
    console.log('[secret-scrubber] Created scrubber.config.json in', userProjectRoot);
  } else {
    console.log('[secret-scrubber] scrubber.config.json already exists');
  }

  // Generate .npmignore if it doesn't exist
  const npmignorePath = path.join(userProjectRoot, '.npmignore');
  if (!fs.existsSync(npmignorePath)) {
    fs.writeFileSync(npmignorePath, DEFAULT_NPMIGNORE, 'utf-8');
    console.log('[secret-scrubber] Created .npmignore in', userProjectRoot);
  } else {
    console.log('[secret-scrubber] .npmignore already exists');
  }

  // Check if .gitignore exists and warn if sensitive patterns missing
  const gitignorePath = path.join(userProjectRoot, '.gitignore');
  if (fs.existsSync(gitignorePath)) {
    const content = fs.readFileSync(gitignorePath, 'utf-8');
    const missingPatterns = [];
    
    const requiredPatterns = ['.env', 'scrubber-report.*', 'scrubbed-*'];
    for (const pattern of requiredPatterns) {
      if (!content.includes(pattern)) {
        missingPatterns.push(pattern);
      }
    }
    
    if (missingPatterns.length > 0) {
      console.log('[secret-scrubber] WARNING: .gitignore missing patterns:', missingPatterns.join(', '));
      console.log('[secret-scrubber] Run `npx scrubber check --fix` to add them');
    }
  } else {
    console.log('[secret-scrubber] No .gitignore found - run `npx scrubber check --fix` to generate one');
  }

  console.log('[secret-scrubber] Setup complete! Run `npx scrubber --help` to get started');
}

main();
